apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: malakbenmansour/pipelines-javascript-docker:$(Build.BuildId)  
        ports:
          - containerPort: 8080  # Port your application listens on
